name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pulumi-infra: 
   runs-on: ubuntu-latest
   outputs:
      matrix: ${{ steps.pulumi-up.outputs.matrix }}
   steps:
   - uses: actions/checkout@v2
   - name: Pulumi Update
     uses: docker://pulumi/actions
     with:
        args: up --yes && echo "pulumi stack output --json > pulumi-output.json"
     env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
        PULUMI_ROOT: Codenames.Infra

   - name: Upload math result for job 1
     uses: actions/upload-artifact@v1
     with:
      name: pulumi-output
      path: pulumi-output.json

  build-deploy:
   runs-on: ubuntu-latest
   needs: pulumi-infra
   steps:
     - name: Download math result for job 1
       uses: actions/download-artifact@v1
       with:
          name: pulumi-output
     - name: Print the final result
       shell: bash
       run: |
          value=`cat pulumi-output/pulumi-output.json`
          echo The result is $value:
