name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pulumi-infra: 
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Pulumi Update
     uses: docker://pulumi/actions
     with:
        args: up --yes && pulumi stack output --json > pulumi-output.json
     env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
        PULUMI_ROOT: Codenames.Infra

   - name: Upload pulumi output artifact
     uses: actions/upload-artifact@v1
     with:
      name: pulumi-output
      path: Codenames.Infra/pulumi-output.json

  build-deploy:
   runs-on: ubuntu-latest
   needs: pulumi-infra
   steps:
     - name: Download pulumi output
       uses: actions/download-artifact@v1
       with:
          name: pulumi-output     
     - name: Assign pulumi output to env variables
       shell: bash
       run: echo "::set-env name=CONTAINER_REGISTRY_NAME::$(jq .ContainerRegistryName pulumi-output/pulumi-output.json)"
            && echo "::set-env name=RESOURCE_GROUP_NAME::$(jq .ResourceGroupName pulumi-output/pulumi-output.json)"
            && echo "::set-env name=CONTAINER_REGISTRY_ADMIN_USERNAME::$(jq .ContainerRegistryAdminUsername pulumi-output/pulumi-output.json)"

     - name: Echo env variable
       shell: bash
       run: echo "${{ env.CONTAINER_REGISTRY_NAME }}" && echo "${{ env.RESOURCE_GROUP_NAME }}" echo "${{ env.CONTAINER_REGISTRY_ADMIN_USERNAME }}"
     - uses: azure/docker-login@v1
       with:
        login-server: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io
        username: ${{ env.CONTAINER_REGISTRY_ADMIN_USERNAME }} 
        password: ${{ secrets.CONTAINER_REGISTRY_ADMIN_PASSWORD }}
