name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pulumi-infra: 
   runs-on: ubuntu-latest
   outputs:
      matrix: ${{ steps.pulumi-up.outputs.matrix }}
   steps:
   - uses: actions/checkout@v2
   - name: Pulumi Update
     id: pulumi-up
     uses: docker://pulumi/actions
     with:
        args: up --yes && echo "::set-output name=matrix::pulumi stack output --json"
     env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
        PULUMI_ROOT: Codenames.Infra

  build-deploy:
   runs-on: ubuntu-latest
   needs: pulumi-infra
   steps:
      - uses: actions/checkout@v2
      - name: Echo matrix
        run: echo ${{ env.PULUMI_OUTPUT }} | jq '.[].name'
        env:
          PULUMI_OUTPUT: ${{ needs.pulumi-infra.pulumi-up.outputs.matrix}}
