name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./Codenames.Service
    - name: Build
      run: dotnet build ./Codenames.Service --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Codenames.Service.Unit.Tests --no-restore --verbosity normal
