name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  pulumi-update: 
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: Codenames.Infra
      - name: Pulumi stack ouput
        run: pulumi stack output --json

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      #with:
       # login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        #username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }} 
        #password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore ./Codenames.Service

    - name: Build
      run: dotnet build ./Codenames.Service --configuration Release --no-restore

    - name: Test
      run: dotnet test ./Codenames.Service.Unit.Tests --no-restore --verbosity normal

    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build ./Codenames.Service -t ${{ env.REGISTRY_NAME }}.azurecr.io/codenamesservice:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/codenamesservice:${{ github.sha }}
